# Setup
title:               mesonscience
tagline:             'science+tech'
description:         'The devblog, from the desk of Ron Bali.'
url:                 https://mesonscience.ml
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ron Bali
  url:               https://mesonscience.ml
  email:             ronbalifunny@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             42
# google_analytics_id: #UA-XXXX-Y
